### ISSUE TITLE
Clarify input field name in PCF 1.11+

### ISSUE THREAD

**Issue by AmberAlston** [pivotalservices/bosh-hm-forwarder-tile#4]
Instructions read, "Enter that IP Address in the "Metrics IP Address" section in the Director Config of the Ops Manager Director tile". You may want to clarify that in PCF 1.11 and later, this is labeled "BOSH HM Forwarder IP Address" in the Director Config

**Comment by mxplusb** [comment]
Thanks @AmberAlston!

**Comment by eamonryan** [comment]
We actually had to make several changes to add compatibility for 1.11 but I did update the README now too. Thanks!
