### ISSUE TITLE
Issue Deploying Tile On PCF 1.11

### ISSUE THREAD

**Issue by CloudPlatform-ESI** [pivotalservices/bosh-hm-forwarder-tile#5]
When trying to deploy this tile on our PCF 1.11 foundation, the apply changes gets an install issue error with the following information.

Started preparing deployment > Preparing deployment. Failed: Unable to process links for deployment. Errors are: - Can't resolve link 'consul_server' in instance group 'hm-forwarder' on job 'consul_agent' in deployment 'bosh-hm-forwarder-18706baef19197dd6e17'. Please make sure the link was provided and shared. (00:00:00)

Error 100: Unable to process links for deployment. Errors are: - Can't resolve link 'consul_server' in instance group 'hm-forwarder' on job 'consul_agent' in deployment 'bosh-hm-forwarder-18706baef19197dd6e17'. Please make sure the link was provided and shared. Task 249999 error

OpsMan Version: 1.11.5
ERT: 1.11.4

**Comment by eamonryan** [comment]
It looks like the way consul works changed significantly in 1.11. I'll look into this.

**Comment by stwomack** [comment]
Any luck, @eamonryan ?

**Comment by eamonryan** [comment]
I've been working on this today, making progress. I think I've gotten around the consul issue but an update to the metron_agent component version to match the 1.11 ERT version is causing another issue that is delaying me. Will update again soon.

**Comment by eamonryan** [comment]
@stwomack Turns out a change in behaviour of the tile generator used to help create this tile is causing the additional issue. I have a fix to test tomorrow and will let you know then.

**Comment by eamonryan** [comment]
New release for PCF 1.11 https://github.com/pivotalservices/bosh-hm-forwarder-tile/releases/tag/0.0.24
